"""empty message

Revision ID: fd8fe195a4d2
Revises: 
Create Date: 2018-12-01 19:44:58.728376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd8fe195a4d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('sent_from_self', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('text', 'image', 'video', name='messagetype'), nullable=False),
    sa.Column('text_body', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_item',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate_item')
    op.drop_table('estimate')
    op.drop_table('chat_message')
    op.drop_table('chat')
    # ### end Alembic commands ###
